//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 12:16:42 PM CEST 
//


package com.spot.on.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.spot.on.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.spot.on.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CourseId }
     * 
     */
    public CourseId createCourseId() {
        return new CourseId();
    }

    /**
     * Create an instance of {@link PersonId }
     * 
     */
    public PersonId createPersonId() {
        return new PersonId();
    }

    /**
     * Create an instance of {@link CourseRequest }
     * 
     */
    public CourseRequest createCourseRequest() {
        return new CourseRequest();
    }

    /**
     * Create an instance of {@link EnrollmentRequest }
     * 
     */
    public EnrollmentRequest createEnrollmentRequest() {
        return new EnrollmentRequest();
    }

    /**
     * Create an instance of {@link WithdrawRequest }
     * 
     */
    public WithdrawRequest createWithdrawRequest() {
        return new WithdrawRequest();
    }

    /**
     * Create an instance of {@link RegisterRequest }
     * 
     */
    public RegisterRequest createRegisterRequest() {
        return new RegisterRequest();
    }

    /**
     * Create an instance of {@link Confirmation }
     * 
     */
    public Confirmation createConfirmation() {
        return new Confirmation();
    }

}
